apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
    name: dev-cluster
    region: sp-south-1
nodeGroups: 
    - name: ng-1-workers
      instanceType: t2.small
      desiredCapacity: 1
      maxSize: 5
      iam:
        withAddonPolicies:
        autoScaler: true
      ssh:
        publicKeyName: eks
      labels:
        nodegroup-type: stateful
        instance-type: onDemandinstance
      availabilityZones: ["ap-south-1b"]
   - name: scale1SpotInstance
     desiredCapacity: 1
     maxSize: 5
     instancesDistribution:
        maxPrice: 0.050
        instanceType: ["t2.small"]
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 0
     availabilityZones: ["ap-south-1a", "ap-south-1b"]
     iam:
        withAddonPolicies:
        autoScaler: true
     ssh: 
      publicKeyName: eks
     labels:
        nodegroup-type: stateless
        instance-type: spotinstance
        
