apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
    name: dev-cluster
    region: sp-south-1
nodeGroups: 
    - name: ng-1-workers
      instanceType: t2.small
      desiredCapacity: 1
      ssh:
        publicKeyName: eks
